### PR TITLE
Document that windows users should use Node 0.12.7

### PR DESCRIPTION
**Pull request by robrich**

### CODE REVIEW

**Comment by LinusU** [comment]
Maybe write it as 0.12.x instead? That way you don't have to update when 0.12.8 comes out :+1:

Also, it would be great to get 4.x support, is it only libusb that needs fixing?

**Comment by johnnyman727** [comment]
Thanks for submitting this @robrich!

Agreed with @LinusU on the version notation. Also, I don't believe having Python installed changes which version of Node you can use.

Lastly, can you add this note for the Linux and OSX screens as well?

@LinusU, I believe libusb is the only limiting factor towards 4.x support :/

**Comment by LinusU** [comment]
Is the same true on OS X and Linux thought? My understanding is that it's only prebuilt binaries which is missing for the newer node version, which is way having Python (which is a part of the build tools) installed changes this. I might be wrong thought...

**Comment by johnnyman727** [comment]
@LinusU that's a good question. I was under the impression that all platforms were waiting on that libusb fix but I haven't tried it myself. I can give it a go tonight or tomorrow.

**Comment by kevinmehall** [comment]
No, node-usb won't build on Node 4.x on any platform because the V8 / NAN API changed.

**Comment by johnnyman727** [comment]
Yep, also just empirically confirmed.

**Comment by LinusU** [comment]
Haha, yes I have actually started porting it myself :facepunch: :dizzy_face: 

Progress can be tracked here: nonolith/node-usb#90

**Comment by robrich** [comment]
PR updated for all 3 OS flavors, and removed the note about Python.

**Comment by johnnyman727** [comment]
Cool thanks @robrich!

**Pull request merged**
